<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Carbon\Carbon;

class Animals extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $animals = [
            [
                'uuid' => 'f47ac10b-58cc-4372-a567-0e02b2c3d4e5',
                'type' => "Dog",
                'name' => "Buddy",
                'is_male' => true,
                'breed' => "Golden Retriever",
                'date_of_birth' => Carbon::parse('2022-05-10'),
                'description' => "Friendly and energetic dog, loves playing fetch.",
                'history' => "Found as a stray.",
                'likes' => "Playing, treats, belly rubs",
                'dislikes' => "Loud noises",
                'arrival_date' => Carbon::parse('2023-01-15'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 1,
            ],
            [
                'uuid' => '8d3b0e9a-f2b1-4c8d-9a0a-1b2c3d4e5f60',
                'type' => "Cat",
                'name' => "Whiskers",
                'is_male' => false,
                'breed' => "Siamese",
                'date_of_birth' => Carbon::parse('2023-01-20'),
                'description' => "Quiet and independent cat, enjoys sunbathing.",
                'history' => "Surrendered by previous owner.",
                'likes' => "Sleeping, tuna, quiet places",
                'dislikes' => "Being picked up",
                'arrival_date' => Carbon::parse('2023-06-01'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 2,
            ],
            [
                'uuid' => '2a1b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
                'type' => "Dog",
                'name' => "Rocky",
                'is_male' => true,
                'breed' => "German Shepherd",
                'date_of_birth' => Carbon::parse('2021-11-01'),
                'description' => "Loyal and protective, needs an experienced owner.",
                'history' => "Rescued from a neglectful situation.",
                'likes' => "Training, long walks",
                'dislikes' => "Strangers initially",
                'arrival_date' => Carbon::parse('2023-03-10'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 3,
            ],
            [
                'uuid' => 'b8c7d6e5-4f3a-2b1c-0d9e-8f7a6b5c4d3e',
                'type' => "Cat",
                'name' => "Luna",
                'is_male' => false,
                'breed' => "Domestic Shorthair",
                'date_of_birth' => Carbon::parse('2024-03-15'),
                'description' => "Playful kitten, very curious.",
                'history' => "Born in the shelter.",
                'likes' => "Toy mice, chasing laser dots",
                'dislikes' => "Being alone",
                'arrival_date' => Carbon::parse('2024-03-15'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 1,
            ],
            [
                'uuid' => '1c2b3a4d-5e6f-7c8b-9d0a-1f2e3d4c5b6a',
                'type' => "Rabbit",
                'name' => "Thumper",
                'is_male' => true,
                'breed' => "Holland Lop",
                'date_of_birth' => Carbon::parse('2023-08-22'),
                'description' => "Shy but sweet rabbit, loves fresh vegetables.",
                'history' => "Found abandoned.",
                'likes' => "Carrots, quiet time",
                'dislikes' => "Sudden movements",
                'arrival_date' => Carbon::parse('2024-01-05'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 2,
            ],
            [
                'uuid' => 'a9b8c7d6-e5f4-3a2b-1c0d-9e8f7a6b5c4d',
                'type' => "Dog",
                'name' => "Daisy",
                'is_male' => false,
                'breed' => "Beagle",
                'date_of_birth' => Carbon::parse('2022-09-01'),
                'description' => "Curious and scent-driven, loves exploring.",
                'history' => "Owner moved and couldn't take her.",
                'likes' => "Sniffing, walks, treats",
                'dislikes' => "Being left alone",
                'arrival_date' => Carbon::parse('2023-11-20'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 3,
            ],
            [
                'uuid' => '3e4d5c6b-7a8f-9e0d-1c2b-3a4f5e6d7c8b',
                'type' => "Cat",
                'name' => "Simba",
                'is_male' => true,
                'breed' => "Maine Coon",
                'date_of_birth' => Carbon::parse('2021-07-18'),
                'description' => "Large and gentle giant, enjoys being brushed.",
                'history' => "Stray found injured.",
                'likes' => "Brushing, high places, naps",
                'dislikes' => "Water",
                'arrival_date' => Carbon::parse('2023-02-14'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 1,
            ],
            [
                'uuid' => '5f6e7d8c-9b0a-1d2c-3b4a-5f6e7d8c9b0a',
                'type' => "Bird",
                'name' => "Sunny",
                'is_male' => null,
                'breed' => "Cockatiel",
                'date_of_birth' => Carbon::parse('2023-04-01'),
                'description' => "Talkative and cheerful, loves millet.",
                'history' => "Found outside.",
                'likes' => "Singing, millet, mirrors",
                'dislikes' => "Sudden loud noises",
                'arrival_date' => Carbon::parse('2024-05-10'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 2,
            ],
            [
                'uuid' => '7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d',
                'type' => "Dog",
                'name' => "Max",
                'is_male' => true,
                'breed' => "Labrador Retriever",
                'date_of_birth' => Carbon::parse('2020-03-05'),
                'description' => "Very friendly and trainable, loves swimming.",
                'history' => "Owner could no longer care for him.",
                'likes' => "Swimming, fetching, people",
                'dislikes' => "Being alone for long periods",
                'arrival_date' => Carbon::parse('2023-09-01'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 3,
            ],
            [
                'uuid' => '9b0a1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d',
                'type' => "Cat",
                'name' => "Cleo",
                'is_male' => false,
                'breed' => "Ragdoll",
                'date_of_birth' => Carbon::parse('2022-12-01'),
                'description' => "Affectionate and laid-back, enjoys being held.",
                'history' => "Found abandoned.",
                'likes' => "Being held, soft beds, gentle petting",
                'dislikes' => "Rough handling",
                'arrival_date' => Carbon::parse('2024-02-20'),
                'is_archived' => false,
                'archived_date' => null,
                'archive_cause' => null,
                'shelter_id' => 1,
            ],
        ];

        foreach ($animals as $animalData) {
            Animal::create([
                'uuid' => $animalData['uuid'],
                'type' => $animalData['type'],
                'name' => $animalData['name'],
                'is_male' => $animalData['is_male'],
                'breed' => $animalData['breed'],
                'date_of_birth' => $animalData['date_of_birth'],
                'description' => $animalData['description'],
                'history' => $animalData['history'],
                'likes' => $animalData['likes'],
                'dislikes' => $animalData['dislikes'],
                'arrival_date' => $animalData['arrival_date'],
                'is_archived' => $animalData['is_archived'],
                'archived_date' => $animalData['archived_date'],
                'archive_cause' => $animalData['archive_cause'],
                'shelter_id' => $animalData['shelter_id'],
            ]);
        }
    }
}
